# Generated by Django 6.0 on 2025-12-24 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workrequest',
            name='unique_request_per_ad_contractor',
        ),
        migrations.AlterUniqueTogether(
            name='workrequest',
            unique_together={('ad', 'contractor')},
        ),
        migrations.AddField(
            model_name='ad',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELED', 'Canceled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_REVIEW', 'In review'), ('DONE', 'Done')], default='OPEN', max_length=20),
        ),
        migrations.RemoveField(
            model_name='workrequest',
            name='is_active',
        ),
    ]
