# Generated by Django 6.0 on 2025-12-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_remove_workrequest_unique_request_per_ad_contractor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('DONE', 'Done'), ('CANCELED', 'Canceled')], default='OPEN', max_length=20),
        ),
    ]
