# Generated by Django 6.0 on 2025-12-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=983719413, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
