# Generated by Django 6.0 on 2025-12-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_response_ticket_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='response',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='ticket',
            name='support_reply',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
